	<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar">
  <div class="sidebar-scroll">
    <nav>
      <ul class="nav">
        <li><a href="index.html" class="active"><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>
        <li>
          <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>
            <span>Kesye</span>
             <i class="icon-submenu lnr lnr-chevron-left"></i></a>
          <div id="subPages" class="collapse ">
            <ul class="nav">
              <li><a href="administration/kesye/new/index.php" class="">Anrejistre</a></li>
              <li><a href="administration/kesye/list/index.php" class="">Liste</a></li>
              <li><a href="page-lockscreen.html" class="">Cheche</a></li>
            </ul>
          </div>
        </li>

        <li>
          <a href="#subPage" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>
            <span>Responsab</span>
             <i class="icon-submenu lnr lnr-chevron-left"></i></a>
          <div id="subPage" class="collapse ">
            <ul class="nav">
              <li><a href="administration/responsab/new/index.php" class="">Anrejistre</a></li>
              <li><a href="administration/responsab/list/index.php" class="">Liste</a></li>
              <li><a href="page-lockscreen.html" class="">Cheche</a></li>
            </ul>
          </div>
        </li>

        <li>
          <a href="#subPag" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>
            <span>Sikisal</span>
             <i class="icon-submenu lnr lnr-chevron-left"></i></a>
          <div id="subPag" class="collapse ">
            <ul class="nav">
              <li><a href="page-profile.html" class="">Anrejistre</a></li>
              <li><a href="page-login.html" class="">Liste</a></li>
              <li><a href="page-lockscreen.html" class="">Cheche</a></li>
            </ul>
          </div>
        </li>

        <li>
          <a href="#subPa" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>
            <span>Fich</span>
             <i class="icon-submenu lnr lnr-chevron-left"></i></a>
          <div id="subPa" class="collapse ">
            <ul class="nav">
              <li><a href="fiche/list/index.php" class="">list</a></li>

            </ul>
          </div>
        </li>

        <li><a href="charts.html" class=""><i class="lnr lnr-chart-bars"></i> <span>Rapo</span></a></li>
        <li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>Konfigiration</span></a></li>

      </ul>
    </nav>
  </div>
</div>
	<!-- END LEFT SIDEBAR -->
